"""email string length inc

Revision ID: 31df50f97b62
Revises: 124f3bffd7ab
Create Date: 2025-06-18 12:57:00.991998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '31df50f97b62'
down_revision: Union[str, None] = '124f3bffd7ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('casino', 'contact_email',
               existing_type=sa.VARCHAR(length=12),
               type_=sqlmodel.sql.sqltypes.AutoString(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('casino', 'contact_email',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=50),
               type_=sa.VARCHAR(length=12),
               existing_nullable=True)
    # ### end Alembic commands ###
